# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install netcat & net-tools
    command: sudo apt-get install -y netcat net-tools
  - init: docker-compose pull
    command: docker-compose up -d --build
